# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/kaloyan/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake

# The command to remove a file.
RM = /home/kaloyan/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kaloyan/linked-list-sprint-project-mbphistory

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kaloyan/linked-list-sprint-project-mbphistory

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/kaloyan/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/kaloyan/.local/share/JetBrains/Toolbox/apps/clion/bin/cmake/linux/x64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kaloyan/linked-list-sprint-project-mbphistory/CMakeFiles /home/kaloyan/linked-list-sprint-project-mbphistory//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kaloyan/linked-list-sprint-project-mbphistory/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mbphistory

# Build rule for target.
mbphistory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mbphistory
.PHONY : mbphistory

# fast build rule for target.
mbphistory/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/build
.PHONY : mbphistory/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/main.cpp.s
.PHONY : main.cpp.s

src/event/event_manager.o: src/event/event_manager.cpp.o
.PHONY : src/event/event_manager.o

# target to build an object file
src/event/event_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/src/event/event_manager.cpp.o
.PHONY : src/event/event_manager.cpp.o

src/event/event_manager.i: src/event/event_manager.cpp.i
.PHONY : src/event/event_manager.i

# target to preprocess a source file
src/event/event_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/src/event/event_manager.cpp.i
.PHONY : src/event/event_manager.cpp.i

src/event/event_manager.s: src/event/event_manager.cpp.s
.PHONY : src/event/event_manager.s

# target to generate assembly for a file
src/event/event_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/src/event/event_manager.cpp.s
.PHONY : src/event/event_manager.cpp.s

src/menu/menu_actions.o: src/menu/menu_actions.cpp.o
.PHONY : src/menu/menu_actions.o

# target to build an object file
src/menu/menu_actions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/src/menu/menu_actions.cpp.o
.PHONY : src/menu/menu_actions.cpp.o

src/menu/menu_actions.i: src/menu/menu_actions.cpp.i
.PHONY : src/menu/menu_actions.i

# target to preprocess a source file
src/menu/menu_actions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/src/menu/menu_actions.cpp.i
.PHONY : src/menu/menu_actions.cpp.i

src/menu/menu_actions.s: src/menu/menu_actions.cpp.s
.PHONY : src/menu/menu_actions.s

# target to generate assembly for a file
src/menu/menu_actions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/src/menu/menu_actions.cpp.s
.PHONY : src/menu/menu_actions.cpp.s

src/menu/menu_display.o: src/menu/menu_display.cpp.o
.PHONY : src/menu/menu_display.o

# target to build an object file
src/menu/menu_display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/src/menu/menu_display.cpp.o
.PHONY : src/menu/menu_display.cpp.o

src/menu/menu_display.i: src/menu/menu_display.cpp.i
.PHONY : src/menu/menu_display.i

# target to preprocess a source file
src/menu/menu_display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/src/menu/menu_display.cpp.i
.PHONY : src/menu/menu_display.cpp.i

src/menu/menu_display.s: src/menu/menu_display.cpp.s
.PHONY : src/menu/menu_display.s

# target to generate assembly for a file
src/menu/menu_display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mbphistory.dir/build.make CMakeFiles/mbphistory.dir/src/menu/menu_display.cpp.s
.PHONY : src/menu/menu_display.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mbphistory"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/event/event_manager.o"
	@echo "... src/event/event_manager.i"
	@echo "... src/event/event_manager.s"
	@echo "... src/menu/menu_actions.o"
	@echo "... src/menu/menu_actions.i"
	@echo "... src/menu/menu_actions.s"
	@echo "... src/menu/menu_display.o"
	@echo "... src/menu/menu_display.i"
	@echo "... src/menu/menu_display.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

